.TH createq 1

.ds )H Linkage Company
.ds ]W Release 0.2.0: August 2000

.SH NAME
createq - Create a receive or send queue.

.SH SYNOPSIS
createq [-r|-s] [QUEUENAME] <REMOTEHOST> <REMOTEQUEUE> <MAXMSGS>

.SH DESCRIPTION
createq is a utility tool to create a queue for receive or send message.
.TP 10
Option

.SH RETURN VALUE
.TP 15
zero         -
Successful completion.
.TP
nonzero      -
Failure. Described in ERRORS.

.SH ERRORS
.TP 30
.ER DTARC_SOCKETWRITE_ERROR
Socket write failed.
.TP
.ER DTARC_SOCKETREAD_ERROR
Socket read failed.

.SH EXAMPLES
.RS 10
DTAHCONN hconn;

DTA_CONN(&hconn,"192.22.33.44");

DTA_SENDMSG(hconn,"myqueue2","hello remote queue!",20,1);

DTA_DISC(hconn);

.SH SEE ALSO


