.TH DTA_CONN 3

.ds )H Linkage Company
.ds ]W Release 0.2.0: August 2000

.SH NAME
DTA_CONN() - Create a connection for communication.

.SH SYNOPSIS
#include "dta.h"

int DTA_CONN(DTAHCONN *hconn,const char *host);

.SH PARAMETERS
.TP 15
hconn        -
Handle of connection.
.TP
host         -
Name or ipaddress of remote host.

.SH DESCRIPTION
DTA_CONN() establish a connection between local host and remote host.
When connection successful, the first parameter hconn will be set.
To compile application, the library libdta.a should be linked.

.SH RETURN VALUE
.TP 15
zero         -
Successful completion.
.TP
nonzero      -
Failure. Described in ERRORS.

.SH ERRORS
.TP 30
.ER DTARC_SERVICEPORT_ERROR
Can't get available port for communication.
.TP
.ER DTARC_REMOTEHOSTIP_ERROR
Remote host IP address not available.
.TP
.ER DTARC_PROTOTYPE_ERROR
Proto type error.
.TP
.ER DTARC_SOCKETCREATE_ERROR
Socket create failed.
.TP
.ER DTARC_SOCKETCONNECT_ERROR
Connect failed.

.SH EXAMPLES
.RS 10
DTAHCONN hconn;

DTA_CONN(&hconn,"192.22.33.44");

//<OR> DTA_CONN(&hconn,"U571");
    .
    .
    .

DTA_DISC(hconn);

.SH SEE ALSO
DTA_DISC(3)



