.TH DTA_CHKERR 3

.ds )H Linkage Company
.ds ]W Release 0.2.0: August 2000

.SH NAME
DTA_CHKERR() - Print error message to standard error output.

.SH SYNOPSIS
#include "dta.h"

void DTA_CHKERR(int err);

.SH PARAMETERS
.TP 15
err          -
DTA function return value declared in "dta.h".

.SH DESCRIPTION
DTA_CHKERR() print error message to standard error output.
The parameter is any return value of DTA function.
To compile application, the library libdta.a should be linked.

.SH EXAMPLES
.RS 10
DTAHCONN hconn;

int ret;

ret=DTA_CONN(&hconn,"192.22.33.44");

if(ret)

{

	DTA_CHKERR(ret);

	exit(-1);

}

    .
    .
    .

DTA_DISC(hconn);

.SH SEE ALSO




