.TH DTA_CLEANQ 3

.ds )H Linkage Company
.ds ]W Release 0.2.0: August 2000

.SH NAME
DTA_CLEANQ() - Clean a queue.

.SH SYNOPSIS
#include "dta.h"

int DTA_CLEANQ(DTAHQUEUE hqueue);

.SH PARAMETERS
.TP 15
hqueue       -
Handle of queue.

.SH DESCRIPTION
DTA_CLEANQ() cleanup died message in a queue openned by DTA_OPENQ().
To compile application, the library libdta.a should be linked.

.SH RETURN VALUE
.TP 15
zero         -
Successful completion.
.TP
nonzero      -
Failure. Described in ERRORS.

.SH ERRORS
.TP 30
.ER DTARC_FILESEEK_ERROR
fseek() failed.
.TP
.ER DTARC_FILEREAD_ERROR
fread() failed.
.TP
.ER DTARC_INTERNAL_ERROR
Internal function call failed.

.SH EXAMPLES
.RS 10
DTAHQUEUE hqueue;

DTA_OPENQ(&hqueue,"myqueue1");

DTA_CLEANQ(hqueue);

DTA_CLOSEQ(hqueue);

.SH SEE ALSO




