.TH DTA_DELMSG 3

.ds )H Linkage Company
.ds ]W Release 0.2.0: August 2000

.SH NAME
DTA_DELMSG() - Delete message in queue.

.SH SYNOPSIS
#include "dta.h"

int DTA_DELMSG(DTAHQUEUE hqueue,long msgn);

.SH PARAMETERS
.TP 15
hqueue       -
Handle of queue.
.TP
msgn         -
Message series number.

.SH DESCRIPTION
DTA_DELMSG() delete message in a queue openned by DTA_OPENQ().
To compile application, the library libdta.a should be linked.

.SH RETURN VALUE
.TP 15
zero         -
Successful completion.
.TP
nonzero      -
Failure. Described in ERRORS.

.SH ERRORS
.TP 30
.ER DTARC_FILESEEK_ERROR
fseek() failed.
.TP
.ER DTARC_FILEREAD_ERROR
fread() failed.
.TP
.ER DTARC_MEMORYALLOC_ERROR
Memory alloc failed.
.TP
.ER DTARC_MESSAGE_DIED
Message is already deleted.
.TP
.ER DTARC_FILEWRITE_ERROR
fwrite() failed.
.TP
.ER DTARC_FILEFLUSH_ERROR
fflush() failed.

.SH EXAMPLES
.RS 10
DTAHQUEUE hqueue;

DTA_OPENQ(&hqueue,"myqueue1");

DTA_DELMSG(hqueue,1);

DTA_CLOSEQ(hqueue);

.SH SEE ALSO




