################################################################################
include $(BUDE_HOME)/stdmake/stdenv

################################################################################
SUBDIRS          =
AFTER_SUMMIT     =

################################################################################
SRCS             = TestApp.cpp


SUBMIT_HDRS      =

#生成目标
PROGRAM          = test
STATIC_LIBRARY   = 
SHARE_LIBRARY    =

#提交相关变量
DEST    = $(WORK_HOME)/bin
DESTLIB = $(WORK_HOME)/lib
DESTINC =
DESTSRC =
DESTDOC =

################################################################################
THE_INCLUDE      = -I./  \
                   -I../ \
                   -I$(WORK_HOME)/include   

THE_LIBPATH      = -L./  


THE_LIB          = -lnsl -loradbi -ljs -ljshlp -lbase -lapp\
                    -lm -llog4cpp  -lclntsh  -lpthread


################################################################################
CXXFLAGS = ${THE_INCLUDE} ${SYSCOMP_INCLUDE} ${ORA_INCLUDE} -DXP_UNIX -DAIX -DJSFILE -DDEBUG -DHAVE_SYS_INTTYPES_H -g -DFP_DEBUG
CCFLAGS  = ${THE_INCLUDE} ${SYSCOMP_INCLUDE} ${ORA_INCLUDE} -DXP_UNIX -DAIX -DJSFILE -DDEBUG -DHAVE_SYS_INTTYPES_H
LDFLAGS  = ${THE_LIBPATH} ${SYSCOMP_LIBPATH} ${ORA_LIBPATH}
LDLIB    = ${THE_LIB} -lcdrbase

################################################################################
include $(BUDE_HOME)/stdmake/stdmk
