/*
 * elfgcchack.h: hack by Arjan van de Ven <arjanv@redhat.com> to speed
 *               up the code when using gcc for call within the library.
 *
 * Based on the analysis http://people.redhat.com/drepper/dsohowto.pdf
 * from Ulrich drepper. Rewritten to be generated from the XML description
 * file for libxml2 API
 * autogenerated with xsltproc doc/elfgcchack.xsl doc/libxml2-api.xml
 */

#include "libxml/c14n.h"
#include "libxml/catalog.h"
#include "libxml/chvalid.h"
#include "libxml/debugXML.h"
#include "libxml/dict.h"
#include "libxml/DOCBparser.h"
#include "libxml/encoding.h"
#include "libxml/entities.h"
#include "libxml/globals.h"
#include "libxml/hash.h"
#include "libxml/HTMLparser.h"
#include "libxml/HTMLtree.h"
#include "libxml/list.h"
#include "libxml/nanoftp.h"
#include "libxml/nanohttp.h"
#include "libxml/parser.h"
#include "libxml/parserInternals.h"
#include "libxml/pattern.h"
#include "libxml/relaxng.h"
#include "libxml/SAX2.h"
#include "libxml/SAX.h"
#include "libxml/schemasInternals.h"
#include "libxml/threads.h"
#include "libxml/tree.h"
#include "libxml/uri.h"
#include "libxml/valid.h"
#include "libxml/xinclude.h"
#include "libxml/xlink.h"
#include "libxml/xmlautomata.h"
#include "libxml/xmlerror.h"
#include "libxml/xmlexports.h"
#include "libxml/xmlIO.h"
#include "libxml/xmlmemory.h"
#include "libxml/xmlreader.h"
#include "libxml/xmlregexp.h"
#include "libxml/xmlsave.h"
#include "libxml/xmlschemas.h"
#include "libxml/xmlschemastypes.h"
#include "libxml/xmlstring.h"
#include "libxml/xmlunicode.h"
#include "libxml/xmlversion.h"
#include "libxml/xmlwriter.h"
#include "libxml/xpath.h"
#include "libxml/xpathInternals.h"
#include "libxml/xpointer.h"

/* special hot spot not exported ones */

extern __typeof (__xmlGenericError) __xmlGenericError__internal_alias __attribute((visibility("hidden")));
extern __typeof (__xmlGenericError) __xmlGenericError __attribute((alias("__xmlGenericError__internal_alias")));
#define __xmlGenericError __xmlGenericError__internal_alias

extern __typeof (__xmlGenericErrorContext) __xmlGenericErrorContext__internal_alias __attribute((visibility("hidden")));
extern __typeof (__xmlGenericErrorContext) __xmlGenericErrorContext __attribute((alias("__xmlGenericErrorContext__internal_alias")));
#define __xmlGenericErrorContext __xmlGenericErrorContext__internal_alias

/* list generated from libxml2-api.xml */

#ifdef LIBXML_DOCB_ENABLED
extern __typeof (docbCreatePushParserCtxt) docbCreatePushParserCtxt__internal_alias __attribute((visibility("hidden")));
extern __typeof (docbCreatePushParserCtxt) docbCreatePushParserCtxt __attribute((alias("docbCreatePushParserCtxt__internal_alias")));
#define docbCreatePushParserCtxt docbCreatePushParserCtxt__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlAttrAllowed) htmlAttrAllowed__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlAttrAllowed) htmlAttrAllowed __attribute((alias("htmlAttrAllowed__internal_alias")));
#define htmlAttrAllowed htmlAttrAllowed__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlAutoCloseTag) htmlAutoCloseTag__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlAutoCloseTag) htmlAutoCloseTag __attribute((alias("htmlAutoCloseTag__internal_alias")));
#define htmlAutoCloseTag htmlAutoCloseTag__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlCreateFileParserCtxt) htmlCreateFileParserCtxt__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlCreateFileParserCtxt) htmlCreateFileParserCtxt __attribute((alias("htmlCreateFileParserCtxt__internal_alias")));
#define htmlCreateFileParserCtxt htmlCreateFileParserCtxt__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlCreateMemoryParserCtxt) htmlCreateMemoryParserCtxt__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlCreateMemoryParserCtxt) htmlCreateMemoryParserCtxt __attribute((alias("htmlCreateMemoryParserCtxt__internal_alias")));
#define htmlCreateMemoryParserCtxt htmlCreateMemoryParserCtxt__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
#ifdef LIBXML_PUSH_ENABLED
extern __typeof (htmlCreatePushParserCtxt) htmlCreatePushParserCtxt__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlCreatePushParserCtxt) htmlCreatePushParserCtxt __attribute((alias("htmlCreatePushParserCtxt__internal_alias")));
#define htmlCreatePushParserCtxt htmlCreatePushParserCtxt__internal_alias
#endif
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlCtxtReadDoc) htmlCtxtReadDoc__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlCtxtReadDoc) htmlCtxtReadDoc __attribute((alias("htmlCtxtReadDoc__internal_alias")));
#define htmlCtxtReadDoc htmlCtxtReadDoc__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlCtxtReadFd) htmlCtxtReadFd__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlCtxtReadFd) htmlCtxtReadFd __attribute((alias("htmlCtxtReadFd__internal_alias")));
#define htmlCtxtReadFd htmlCtxtReadFd__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlCtxtReadFile) htmlCtxtReadFile__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlCtxtReadFile) htmlCtxtReadFile __attribute((alias("htmlCtxtReadFile__internal_alias")));
#define htmlCtxtReadFile htmlCtxtReadFile__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlCtxtReadIO) htmlCtxtReadIO__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlCtxtReadIO) htmlCtxtReadIO __attribute((alias("htmlCtxtReadIO__internal_alias")));
#define htmlCtxtReadIO htmlCtxtReadIO__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlCtxtReadMemory) htmlCtxtReadMemory__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlCtxtReadMemory) htmlCtxtReadMemory __attribute((alias("htmlCtxtReadMemory__internal_alias")));
#define htmlCtxtReadMemory htmlCtxtReadMemory__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlCtxtReset) htmlCtxtReset__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlCtxtReset) htmlCtxtReset __attribute((alias("htmlCtxtReset__internal_alias")));
#define htmlCtxtReset htmlCtxtReset__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlCtxtUseOptions) htmlCtxtUseOptions__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlCtxtUseOptions) htmlCtxtUseOptions __attribute((alias("htmlCtxtUseOptions__internal_alias")));
#define htmlCtxtUseOptions htmlCtxtUseOptions__internal_alias
#endif

extern __typeof (htmlDefaultSAXHandlerInit) htmlDefaultSAXHandlerInit__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlDefaultSAXHandlerInit) htmlDefaultSAXHandlerInit __attribute((alias("htmlDefaultSAXHandlerInit__internal_alias")));
#define htmlDefaultSAXHandlerInit htmlDefaultSAXHandlerInit__internal_alias

#ifdef LIBXML_HTML_ENABLED
#ifdef LIBXML_OUTPUT_ENABLED
extern __typeof (htmlDocContentDumpFormatOutput) htmlDocContentDumpFormatOutput__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlDocContentDumpFormatOutput) htmlDocContentDumpFormatOutput __attribute((alias("htmlDocContentDumpFormatOutput__internal_alias")));
#define htmlDocContentDumpFormatOutput htmlDocContentDumpFormatOutput__internal_alias
#endif
#endif

#ifdef LIBXML_HTML_ENABLED
#ifdef LIBXML_OUTPUT_ENABLED
extern __typeof (htmlDocContentDumpOutput) htmlDocContentDumpOutput__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlDocContentDumpOutput) htmlDocContentDumpOutput __attribute((alias("htmlDocContentDumpOutput__internal_alias")));
#define htmlDocContentDumpOutput htmlDocContentDumpOutput__internal_alias
#endif
#endif

#ifdef LIBXML_HTML_ENABLED
#ifdef LIBXML_OUTPUT_ENABLED
extern __typeof (htmlDocDump) htmlDocDump__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlDocDump) htmlDocDump __attribute((alias("htmlDocDump__internal_alias")));
#define htmlDocDump htmlDocDump__internal_alias
#endif
#endif

#ifdef LIBXML_HTML_ENABLED
#ifdef LIBXML_OUTPUT_ENABLED
extern __typeof (htmlDocDumpMemory) htmlDocDumpMemory__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlDocDumpMemory) htmlDocDumpMemory __attribute((alias("htmlDocDumpMemory__internal_alias")));
#define htmlDocDumpMemory htmlDocDumpMemory__internal_alias
#endif
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlElementAllowedHere) htmlElementAllowedHere__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlElementAllowedHere) htmlElementAllowedHere __attribute((alias("htmlElementAllowedHere__internal_alias")));
#define htmlElementAllowedHere htmlElementAllowedHere__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlElementStatusHere) htmlElementStatusHere__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlElementStatusHere) htmlElementStatusHere __attribute((alias("htmlElementStatusHere__internal_alias")));
#define htmlElementStatusHere htmlElementStatusHere__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlEncodeEntities) htmlEncodeEntities__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlEncodeEntities) htmlEncodeEntities __attribute((alias("htmlEncodeEntities__internal_alias")));
#define htmlEncodeEntities htmlEncodeEntities__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlEntityLookup) htmlEntityLookup__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlEntityLookup) htmlEntityLookup __attribute((alias("htmlEntityLookup__internal_alias")));
#define htmlEntityLookup htmlEntityLookup__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlEntityValueLookup) htmlEntityValueLookup__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlEntityValueLookup) htmlEntityValueLookup __attribute((alias("htmlEntityValueLookup__internal_alias")));
#define htmlEntityValueLookup htmlEntityValueLookup__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlFreeParserCtxt) htmlFreeParserCtxt__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlFreeParserCtxt) htmlFreeParserCtxt __attribute((alias("htmlFreeParserCtxt__internal_alias")));
#define htmlFreeParserCtxt htmlFreeParserCtxt__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlGetMetaEncoding) htmlGetMetaEncoding__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlGetMetaEncoding) htmlGetMetaEncoding __attribute((alias("htmlGetMetaEncoding__internal_alias")));
#define htmlGetMetaEncoding htmlGetMetaEncoding__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlHandleOmittedElem) htmlHandleOmittedElem__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlHandleOmittedElem) htmlHandleOmittedElem __attribute((alias("htmlHandleOmittedElem__internal_alias")));
#define htmlHandleOmittedElem htmlHandleOmittedElem__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlInitAutoClose) htmlInitAutoClose__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlInitAutoClose) htmlInitAutoClose __attribute((alias("htmlInitAutoClose__internal_alias")));
#define htmlInitAutoClose htmlInitAutoClose__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlIsAutoClosed) htmlIsAutoClosed__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlIsAutoClosed) htmlIsAutoClosed __attribute((alias("htmlIsAutoClosed__internal_alias")));
#define htmlIsAutoClosed htmlIsAutoClosed__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlIsBooleanAttr) htmlIsBooleanAttr__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlIsBooleanAttr) htmlIsBooleanAttr __attribute((alias("htmlIsBooleanAttr__internal_alias")));
#define htmlIsBooleanAttr htmlIsBooleanAttr__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlIsScriptAttribute) htmlIsScriptAttribute__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlIsScriptAttribute) htmlIsScriptAttribute __attribute((alias("htmlIsScriptAttribute__internal_alias")));
#define htmlIsScriptAttribute htmlIsScriptAttribute__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlNewDoc) htmlNewDoc__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlNewDoc) htmlNewDoc __attribute((alias("htmlNewDoc__internal_alias")));
#define htmlNewDoc htmlNewDoc__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlNewDocNoDtD) htmlNewDocNoDtD__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlNewDocNoDtD) htmlNewDocNoDtD __attribute((alias("htmlNewDocNoDtD__internal_alias")));
#define htmlNewDocNoDtD htmlNewDocNoDtD__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
#ifdef LIBXML_OUTPUT_ENABLED
extern __typeof (htmlNodeDump) htmlNodeDump__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlNodeDump) htmlNodeDump __attribute((alias("htmlNodeDump__internal_alias")));
#define htmlNodeDump htmlNodeDump__internal_alias
#endif
#endif

#ifdef LIBXML_HTML_ENABLED
#ifdef LIBXML_OUTPUT_ENABLED
extern __typeof (htmlNodeDumpFile) htmlNodeDumpFile__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlNodeDumpFile) htmlNodeDumpFile __attribute((alias("htmlNodeDumpFile__internal_alias")));
#define htmlNodeDumpFile htmlNodeDumpFile__internal_alias
#endif
#endif

#ifdef LIBXML_HTML_ENABLED
#ifdef LIBXML_OUTPUT_ENABLED
extern __typeof (htmlNodeDumpFileFormat) htmlNodeDumpFileFormat__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlNodeDumpFileFormat) htmlNodeDumpFileFormat __attribute((alias("htmlNodeDumpFileFormat__internal_alias")));
#define htmlNodeDumpFileFormat htmlNodeDumpFileFormat__internal_alias
#endif
#endif

#ifdef LIBXML_HTML_ENABLED
#ifdef LIBXML_OUTPUT_ENABLED
extern __typeof (htmlNodeDumpFormatOutput) htmlNodeDumpFormatOutput__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlNodeDumpFormatOutput) htmlNodeDumpFormatOutput __attribute((alias("htmlNodeDumpFormatOutput__internal_alias")));
#define htmlNodeDumpFormatOutput htmlNodeDumpFormatOutput__internal_alias
#endif
#endif

#ifdef LIBXML_HTML_ENABLED
#ifdef LIBXML_OUTPUT_ENABLED
extern __typeof (htmlNodeDumpOutput) htmlNodeDumpOutput__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlNodeDumpOutput) htmlNodeDumpOutput __attribute((alias("htmlNodeDumpOutput__internal_alias")));
#define htmlNodeDumpOutput htmlNodeDumpOutput__internal_alias
#endif
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlNodeStatus) htmlNodeStatus__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlNodeStatus) htmlNodeStatus __attribute((alias("htmlNodeStatus__internal_alias")));
#define htmlNodeStatus htmlNodeStatus__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlParseCharRef) htmlParseCharRef__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlParseCharRef) htmlParseCharRef __attribute((alias("htmlParseCharRef__internal_alias")));
#define htmlParseCharRef htmlParseCharRef__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
#ifdef LIBXML_PUSH_ENABLED
extern __typeof (htmlParseChunk) htmlParseChunk__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlParseChunk) htmlParseChunk __attribute((alias("htmlParseChunk__internal_alias")));
#define htmlParseChunk htmlParseChunk__internal_alias
#endif
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlParseDoc) htmlParseDoc__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlParseDoc) htmlParseDoc __attribute((alias("htmlParseDoc__internal_alias")));
#define htmlParseDoc htmlParseDoc__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlParseDocument) htmlParseDocument__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlParseDocument) htmlParseDocument __attribute((alias("htmlParseDocument__internal_alias")));
#define htmlParseDocument htmlParseDocument__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlParseElement) htmlParseElement__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlParseElement) htmlParseElement __attribute((alias("htmlParseElement__internal_alias")));
#define htmlParseElement htmlParseElement__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlParseEntityRef) htmlParseEntityRef__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlParseEntityRef) htmlParseEntityRef __attribute((alias("htmlParseEntityRef__internal_alias")));
#define htmlParseEntityRef htmlParseEntityRef__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlParseFile) htmlParseFile__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlParseFile) htmlParseFile __attribute((alias("htmlParseFile__internal_alias")));
#define htmlParseFile htmlParseFile__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlReadDoc) htmlReadDoc__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlReadDoc) htmlReadDoc __attribute((alias("htmlReadDoc__internal_alias")));
#define htmlReadDoc htmlReadDoc__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlReadFd) htmlReadFd__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlReadFd) htmlReadFd __attribute((alias("htmlReadFd__internal_alias")));
#define htmlReadFd htmlReadFd__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlReadFile) htmlReadFile__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlReadFile) htmlReadFile __attribute((alias("htmlReadFile__internal_alias")));
#define htmlReadFile htmlReadFile__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlReadIO) htmlReadIO__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlReadIO) htmlReadIO __attribute((alias("htmlReadIO__internal_alias")));
#define htmlReadIO htmlReadIO__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlReadMemory) htmlReadMemory__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlReadMemory) htmlReadMemory __attribute((alias("htmlReadMemory__internal_alias")));
#define htmlReadMemory htmlReadMemory__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlSAXParseDoc) htmlSAXParseDoc__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlSAXParseDoc) htmlSAXParseDoc __attribute((alias("htmlSAXParseDoc__internal_alias")));
#define htmlSAXParseDoc htmlSAXParseDoc__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlSAXParseFile) htmlSAXParseFile__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlSAXParseFile) htmlSAXParseFile __attribute((alias("htmlSAXParseFile__internal_alias")));
#define htmlSAXParseFile htmlSAXParseFile__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
#ifdef LIBXML_OUTPUT_ENABLED
extern __typeof (htmlSaveFile) htmlSaveFile__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlSaveFile) htmlSaveFile __attribute((alias("htmlSaveFile__internal_alias")));
#define htmlSaveFile htmlSaveFile__internal_alias
#endif
#endif

#ifdef LIBXML_HTML_ENABLED
#ifdef LIBXML_OUTPUT_ENABLED
extern __typeof (htmlSaveFileEnc) htmlSaveFileEnc__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlSaveFileEnc) htmlSaveFileEnc __attribute((alias("htmlSaveFileEnc__internal_alias")));
#define htmlSaveFileEnc htmlSaveFileEnc__internal_alias
#endif
#endif

#ifdef LIBXML_HTML_ENABLED
#ifdef LIBXML_OUTPUT_ENABLED
extern __typeof (htmlSaveFileFormat) htmlSaveFileFormat__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlSaveFileFormat) htmlSaveFileFormat __attribute((alias("htmlSaveFileFormat__internal_alias")));
#define htmlSaveFileFormat htmlSaveFileFormat__internal_alias
#endif
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlSetMetaEncoding) htmlSetMetaEncoding__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlSetMetaEncoding) htmlSetMetaEncoding __attribute((alias("htmlSetMetaEncoding__internal_alias")));
#define htmlSetMetaEncoding htmlSetMetaEncoding__internal_alias
#endif

#ifdef LIBXML_HTML_ENABLED
extern __typeof (htmlTagLookup) htmlTagLookup__internal_alias __attribute((visibility("hidden")));
extern __typeof (htmlTagLookup) htmlTagLookup __attribute((alias("htmlTagLookup__internal_alias")));
#define htmlTagLookup htmlTagLookup__internal_alias
#endif

extern __typeof (inputPop) inputPop__internal_alias __attribute((visibility("hidden")));
extern __typeof (inputPop) inputPop __attribute((alias("inputPop__internal_alias")));
#define inputPop inputPop__internal_alias

extern __typeof (inputPush) inputPush__internal_alias __attribute((visibility("hidden")));
extern __typeof (inputPush) inputPush __attribute((alias("inputPush__internal_alias")));
#define inputPush inputPush__internal_alias

extern __typeof (namePop) namePop__internal_alias __attribute((visibility("hidden")));
extern __typeof (namePop) namePop __attribute((alias("namePop__internal_alias")));
#define namePop namePop__internal_alias

extern __typeof (namePush) namePush__internal_alias __attribute((visibility("hidden")));
extern __typeof (namePush) namePush __attribute((alias("namePush__internal_alias")));
#define namePush namePush__internal_alias

extern __typeof (nodePop) nodePop__internal_alias __attribute((visibility("hidden")));
extern __typeof (nodePop) nodePop __attribute((alias("nodePop__internal_alias")));
#define nodePop nodePop__internal_alias

extern __typeof (nodePush) nodePush__internal_alias __attribute((visibility("hidden")));
extern __typeof (nodePush) nodePush __attribute((alias("nodePush__internal_alias")));
#define nodePush nodePush__internal_alias

#ifdef LIBXML_XPATH_ENABLED
extern __typeof (valuePop) valuePop__internal_alias __attribute((visibility("hidden")));
extern __typeof (valuePop) valuePop __attribute((alias("valuePop__internal_alias")));
#define valuePop valuePop__internal_alias
#endif

#ifdef LIBXML_XPATH_ENABLED
extern __typeof (valuePush) valuePush__internal_alias __attribute((visibility("hidden")));
extern __typeof (valuePush) valuePush __attribute((alias("valuePush__internal_alias")));
#define valuePush valuePush__internal_alias
#endif

#ifdef LIBXML_CATALOG_ENABLED
extern __typeof (xmlACatalogAdd) xmlACatalogAdd__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlACatalogAdd) xmlACatalogAdd __attribute((alias("xmlACatalogAdd__internal_alias")));
#define xmlACatalogAdd xmlACatalogAdd__internal_alias
#endif

#ifdef LIBXML_CATALOG_ENABLED
#ifdef LIBXML_OUTPUT_ENABLED
extern __typeof (xmlACatalogDump) xmlACatalogDump__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlACatalogDump) xmlACatalogDump __attribute((alias("xmlACatalogDump__internal_alias")));
#define xmlACatalogDump xmlACatalogDump__internal_alias
#endif
#endif

#ifdef LIBXML_CATALOG_ENABLED
extern __typeof (xmlACatalogRemove) xmlACatalogRemove__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlACatalogRemove) xmlACatalogRemove __attribute((alias("xmlACatalogRemove__internal_alias")));
#define xmlACatalogRemove xmlACatalogRemove__internal_alias
#endif

#ifdef LIBXML_CATALOG_ENABLED
extern __typeof (xmlACatalogResolve) xmlACatalogResolve__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlACatalogResolve) xmlACatalogResolve __attribute((alias("xmlACatalogResolve__internal_alias")));
#define xmlACatalogResolve xmlACatalogResolve__internal_alias
#endif

#ifdef LIBXML_CATALOG_ENABLED
extern __typeof (xmlACatalogResolvePublic) xmlACatalogResolvePublic__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlACatalogResolvePublic) xmlACatalogResolvePublic __attribute((alias("xmlACatalogResolvePublic__internal_alias")));
#define xmlACatalogResolvePublic xmlACatalogResolvePublic__internal_alias
#endif

#ifdef LIBXML_CATALOG_ENABLED
extern __typeof (xmlACatalogResolveSystem) xmlACatalogResolveSystem__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlACatalogResolveSystem) xmlACatalogResolveSystem __attribute((alias("xmlACatalogResolveSystem__internal_alias")));
#define xmlACatalogResolveSystem xmlACatalogResolveSystem__internal_alias
#endif

#ifdef LIBXML_CATALOG_ENABLED
extern __typeof (xmlACatalogResolveURI) xmlACatalogResolveURI__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlACatalogResolveURI) xmlACatalogResolveURI __attribute((alias("xmlACatalogResolveURI__internal_alias")));
#define xmlACatalogResolveURI xmlACatalogResolveURI__internal_alias
#endif

extern __typeof (xmlAddAttributeDecl) xmlAddAttributeDecl__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlAddAttributeDecl) xmlAddAttributeDecl __attribute((alias("xmlAddAttributeDecl__internal_alias")));
#define xmlAddAttributeDecl xmlAddAttributeDecl__internal_alias

extern __typeof (xmlAddChild) xmlAddChild__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlAddChild) xmlAddChild __attribute((alias("xmlAddChild__internal_alias")));
#define xmlAddChild xmlAddChild__internal_alias

extern __typeof (xmlAddChildList) xmlAddChildList__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlAddChildList) xmlAddChildList __attribute((alias("xmlAddChildList__internal_alias")));
#define xmlAddChildList xmlAddChildList__internal_alias

extern __typeof (xmlAddDocEntity) xmlAddDocEntity__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlAddDocEntity) xmlAddDocEntity __attribute((alias("xmlAddDocEntity__internal_alias")));
#define xmlAddDocEntity xmlAddDocEntity__internal_alias

extern __typeof (xmlAddDtdEntity) xmlAddDtdEntity__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlAddDtdEntity) xmlAddDtdEntity __attribute((alias("xmlAddDtdEntity__internal_alias")));
#define xmlAddDtdEntity xmlAddDtdEntity__internal_alias

extern __typeof (xmlAddElementDecl) xmlAddElementDecl__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlAddElementDecl) xmlAddElementDecl __attribute((alias("xmlAddElementDecl__internal_alias")));
#define xmlAddElementDecl xmlAddElementDecl__internal_alias

extern __typeof (xmlAddEncodingAlias) xmlAddEncodingAlias__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlAddEncodingAlias) xmlAddEncodingAlias __attribute((alias("xmlAddEncodingAlias__internal_alias")));
#define xmlAddEncodingAlias xmlAddEncodingAlias__internal_alias

extern __typeof (xmlAddID) xmlAddID__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlAddID) xmlAddID __attribute((alias("xmlAddID__internal_alias")));
#define xmlAddID xmlAddID__internal_alias

extern __typeof (xmlAddNextSibling) xmlAddNextSibling__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlAddNextSibling) xmlAddNextSibling __attribute((alias("xmlAddNextSibling__internal_alias")));
#define xmlAddNextSibling xmlAddNextSibling__internal_alias

extern __typeof (xmlAddNotationDecl) xmlAddNotationDecl__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlAddNotationDecl) xmlAddNotationDecl __attribute((alias("xmlAddNotationDecl__internal_alias")));
#define xmlAddNotationDecl xmlAddNotationDecl__internal_alias

#ifdef LIBXML_TREE_ENABLED
extern __typeof (xmlAddPrevSibling) xmlAddPrevSibling__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlAddPrevSibling) xmlAddPrevSibling __attribute((alias("xmlAddPrevSibling__internal_alias")));
#define xmlAddPrevSibling xmlAddPrevSibling__internal_alias
#endif

extern __typeof (xmlAddRef) xmlAddRef__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlAddRef) xmlAddRef __attribute((alias("xmlAddRef__internal_alias")));
#define xmlAddRef xmlAddRef__internal_alias

extern __typeof (xmlAddSibling) xmlAddSibling__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlAddSibling) xmlAddSibling __attribute((alias("xmlAddSibling__internal_alias")));
#define xmlAddSibling xmlAddSibling__internal_alias

#ifdef LIBXML_OUTPUT_ENABLED
extern __typeof (xmlAllocOutputBuffer) xmlAllocOutputBuffer__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlAllocOutputBuffer) xmlAllocOutputBuffer __attribute((alias("xmlAllocOutputBuffer__internal_alias")));
#define xmlAllocOutputBuffer xmlAllocOutputBuffer__internal_alias
#endif

extern __typeof (xmlAllocParserInputBuffer) xmlAllocParserInputBuffer__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlAllocParserInputBuffer) xmlAllocParserInputBuffer __attribute((alias("xmlAllocParserInputBuffer__internal_alias")));
#define xmlAllocParserInputBuffer xmlAllocParserInputBuffer__internal_alias

extern __typeof (xmlAttrSerializeTxtContent) xmlAttrSerializeTxtContent__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlAttrSerializeTxtContent) xmlAttrSerializeTxtContent __attribute((alias("xmlAttrSerializeTxtContent__internal_alias")));
#define xmlAttrSerializeTxtContent xmlAttrSerializeTxtContent__internal_alias

#ifdef LIBXML_AUTOMATA_ENABLED
extern __typeof (xmlAutomataCompile) xmlAutomataCompile__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlAutomataCompile) xmlAutomataCompile __attribute((alias("xmlAutomataCompile__internal_alias")));
#define xmlAutomataCompile xmlAutomataCompile__internal_alias
#endif

#ifdef LIBXML_AUTOMATA_ENABLED
extern __typeof (xmlAutomataGetInitState) xmlAutomataGetInitState__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlAutomataGetInitState) xmlAutomataGetInitState __attribute((alias("xmlAutomataGetInitState__internal_alias")));
#define xmlAutomataGetInitState xmlAutomataGetInitState__internal_alias
#endif

#ifdef LIBXML_AUTOMATA_ENABLED
extern __typeof (xmlAutomataIsDeterminist) xmlAutomataIsDeterminist__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlAutomataIsDeterminist) xmlAutomataIsDeterminist __attribute((alias("xmlAutomataIsDeterminist__internal_alias")));
#define xmlAutomataIsDeterminist xmlAutomataIsDeterminist__internal_alias
#endif

#ifdef LIBXML_AUTOMATA_ENABLED
extern __typeof (xmlAutomataNewAllTrans) xmlAutomataNewAllTrans__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlAutomataNewAllTrans) xmlAutomataNewAllTrans __attribute((alias("xmlAutomataNewAllTrans__internal_alias")));
#define xmlAutomataNewAllTrans xmlAutomataNewAllTrans__internal_alias
#endif

#ifdef LIBXML_AUTOMATA_ENABLED
extern __typeof (xmlAutomataNewCountTrans) xmlAutomataNewCountTrans__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlAutomataNewCountTrans) xmlAutomataNewCountTrans __attribute((alias("xmlAutomataNewCountTrans__internal_alias")));
#define xmlAutomataNewCountTrans xmlAutomataNewCountTrans__internal_alias
#endif

#ifdef LIBXML_AUTOMATA_ENABLED
extern __typeof (xmlAutomataNewCountTrans2) xmlAutomataNewCountTrans2__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlAutomataNewCountTrans2) xmlAutomataNewCountTrans2 __attribute((alias("xmlAutomataNewCountTrans2__internal_alias")));
#define xmlAutomataNewCountTrans2 xmlAutomataNewCountTrans2__internal_alias
#endif

#ifdef LIBXML_AUTOMATA_ENABLED
extern __typeof (xmlAutomataNewCountedTrans) xmlAutomataNewCountedTrans__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlAutomataNewCountedTrans) xmlAutomataNewCountedTrans __attribute((alias("xmlAutomataNewCountedTrans__internal_alias")));
#define xmlAutomataNewCountedTrans xmlAutomataNewCountedTrans__internal_alias
#endif

#ifdef LIBXML_AUTOMATA_ENABLED
extern __typeof (xmlAutomataNewCounter) xmlAutomataNewCounter__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlAutomataNewCounter) xmlAutomataNewCounter __attribute((alias("xmlAutomataNewCounter__internal_alias")));
#define xmlAutomataNewCounter xmlAutomataNewCounter__internal_alias
#endif

#ifdef LIBXML_AUTOMATA_ENABLED
extern __typeof (xmlAutomataNewCounterTrans) xmlAutomataNewCounterTrans__internal_alias __attribute((visibility("hidden")));
extern __typeof (xmlAutomataNewCounterTrans) xmlAutomataNewCounterTrans __attribute((alias("xmlAutomataNewCounterTrans__internal_alias")));
#define xmlAutomataNewCounterTrans xmlAutomataNewCounterTrans__intern