.PHONY: clean All

All:
	@echo "----------Building project:[ First - Debug ]----------"
	@$(MAKE) -f  "First.mk"
clean:
	@echo "----------Cleaning project:[ First - Debug ]----------"
	@$(MAKE) -f  "First.mk" clean
