/* Generated by KongDB@lianchuang.com */
#ifndef DBPASSOPER_H
#define DBPASSOPER_H

#include <string>

using namespace std;

//数据库登录信息结构体
struct DBPass
{
	//数据库编码
	string Code;
	//数据库主机地址
	string Host;
	//数据库sid
	string ServerName;
	//用户名
	string UserName ;
	//加密后的密码
	string Passwd ;
	//解密后的密码
	string DecPasswd;
};

class DBPassOper
{
	public:
		virtual ~DBPassOper(){};
		/**
     * 根据数据库编码及用户名获取数据库访问信息
     * @param pass 					输出pass对象的引用
     * @param strDBCode 		输入数据库编码
     * @param strDBUserName 输入数据库用户名
     * @return: true 成功 false 失败
     */
		virtual bool GetDBPass(DBPass& dbPass, const string &strDBCode, const string &strDBUserName) = 0;	
		
		static DBPassOper* getOper(const string& opt = "Default");
};

extern "C" bool GetDBPass(DBPass& dbpass, const string &strDBCode, const string &strDBUserName);

#endif /* DBPASSOPER_H_INCLUDED */
