/* Generated by KongDB@lianchuang.com */
#ifndef HOSTPASSOPER_H
#define HOSTPASSOPER_H

#include <string>

using namespace std;

//主机登录信息结构体
struct HostInfo
{
	//主机名
	string Name;
	//IP
	string Ip;
	//用户名
	string UserName ;
	//加密后的密码
	string Passwd ;
	//解密后的密码
	string Remark;
	//解密后的密码
	string DecPasswd ;
};

class HostPassOper
{
	public:
		virtual ~HostPassOper(){};
		/**
     * 根据主机名及用户名获取主机访问信息
     * @param pass 					输出主机对象的引用
     * @param strDBCode 		输入主机名
     * @param strDBUserName 输入主机用户名
     * @return: true 成功 false 失败
     */
		virtual bool GetHostPass(HostInfo& hostInfo, const string &strHostName, const string &strHostUserName) = 0;	
		
		static HostPassOper* getOper(const string& opt = "Default");
};

extern "C" bool GetHostPass(HostInfo& hostInfo, const string &strHostName, const string &strHostUserName);

#endif /* HOSTPASSOPER_H_INCLUDED */
