#ifndef __TRANSFERAPPERROR_H__
#define __TRANSFERAPPERROR_H__

const int TRANSFERBASE = 1900;

const int ERROR_FTCONTROLLER_INIT = TRANSFERBASE + 1; // 初始化 FTCONTROLLER 失败
const int ERROR_FTCONTROLLER_EXEC = TRANSFERBASE + 2; // 执行 FTCONTROLLER 失败

#endif // __TRANSFERAPPERROR_H__
