ln -s -f $BUDE_HOME/frame/mwsvc/bin/qbllcdr3l3server qbllcdr3l3server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qbllcdr3l4server qbllcdr3l4server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qbllcdr3l2server qbllcdr3l2server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qbllcdr3l1server qbllcdr3l1server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qbllcdr2l4server qbllcdr2l4server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qbllcdr2l3server qbllcdr2l3server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qbllcdr2l2server qbllcdr2l2server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qbllcdr2l1server qbllcdr2l1server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qbllcdr1l3server qbllcdr1l3server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qbllcdr1l4server qbllcdr1l4server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qbllcdr1l1server qbllcdr1l1server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qbllcdr1l2server qbllcdr1l2server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qbllcrm1l2server qbllcrm1l2server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qbllcrm1l3server qbllcrm1l3server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qbllcrm1l4server qbllcrm1l4server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qbllcrm1l1server qbllcrm1l1server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xsacenl4server   xsacenl4server   
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xsacenl1server   xsacenl1server   
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xsacenl2server   xsacenl2server   
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xsacenl3server   xsacenl3server   
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tsacenl3server   tsacenl3server   
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tsacenl4server   tsacenl4server   
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tsacenl1server   tsacenl1server   
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tsacenl2server   tsacenl2server   
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qsacenl2server   qsacenl2server   
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qsacenl3server   qsacenl3server   
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qsacenl4server   qsacenl4server   
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qsacenl1server   qsacenl1server   
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xitfuifl4server  xitfuifl4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xitfuifl1server  xitfuifl1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xitfuifl2server  xitfuifl2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xitfuifl3server  xitfuifl3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/titfuifl2server  titfuifl2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/titfuifl3server  titfuifl3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/titfuifl4server  titfuifl4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qitfuifl4server  qitfuifl4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/titfuifl1server  titfuifl1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qitfuifl1server  qitfuifl1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qitfuifl2server  qitfuifl2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qitfuifl3server  qitfuifl3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xamcbs1l2server  xamcbs1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xamcbs1l3server  xamcbs1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xamcbs1l4server  xamcbs1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tamcbs1l4server  tamcbs1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xamcbs1l1server  xamcbs1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tamcbs1l1server  tamcbs1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tamcbs1l2server  tamcbs1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tamcbs1l3server  tamcbs1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qamcbs1l2server  qamcbs1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qamcbs1l3server  qamcbs1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qamcbs1l4server  qamcbs1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qamcbs1l1server  qamcbs1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xsmcrm1l3server  xsmcrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xsmcrm1l4server  xsmcrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xsmcrm1l1server  xsmcrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xsmcrm1l2server  xsmcrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tsmcrm1l1server  tsmcrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tsmcrm1l2server  tsmcrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tsmcrm1l3server  tsmcrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tsmcrm1l4server  tsmcrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qsmcrm1l2server  qsmcrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qsmcrm1l3server  qsmcrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qsmcrm1l4server  qsmcrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qsmcrm1l1server  qsmcrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xrmcrm1l4server  xrmcrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xrmcrm1l1server  xrmcrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xrmcrm1l2server  xrmcrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xrmcrm1l3server  xrmcrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/trmcrm1l2server  trmcrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/trmcrm1l3server  trmcrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/trmcrm1l4server  trmcrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qrmcrm1l3server  qrmcrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qrmcrm1l4server  qrmcrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/trmcrm1l1server  trmcrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qrmcrm1l1server  qrmcrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qrmcrm1l2server  qrmcrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xracrm1l2server  xracrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xracrm1l3server  xracrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xracrm1l4server  xracrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tracrm1l2server  tracrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tracrm1l3server  tracrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tracrm1l4server  tracrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xracrm1l1server  xracrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qracrm1l4server  qracrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tracrm1l1server  tracrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qracrm1l1server  qracrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qracrm1l2server  qracrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qracrm1l3server  qracrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xpucrm1l2server  xpucrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xpucrm1l3server  xpucrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xpucrm1l4server  xpucrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tpucrm1l4server  tpucrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xpucrm1l1server  xpucrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tpucrm1l1server  tpucrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tpucrm1l2server  tpucrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tpucrm1l3server  tpucrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qpucrm1l2server  qpucrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qpucrm1l3server  qpucrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qpucrm1l4server  qpucrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qpucrm1l1server  qpucrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xplcrm1l3server  xplcrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xplcrm1l4server  xplcrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tplcrm1l4server  tplcrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xplcrm1l1server  xplcrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xplcrm1l2server  xplcrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tplcrm1l2server  tplcrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tplcrm1l3server  tplcrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qplcrm1l3server  qplcrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qplcrm1l4server  qplcrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tplcrm1l1server  tplcrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qplcrm1l2server  qplcrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qplcrm1l1server  qplcrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xitfcrm1l4server xitfcrm1l4server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xitfcrm1l3server xitfcrm1l3server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xitfcrm1l1server xitfcrm1l1server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xitfcrm1l2server xitfcrm1l2server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/titfcrm1l4server titfcrm1l4server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/titfcrm1l3server titfcrm1l3server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qitfcrm1l4server qitfcrm1l4server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/titfcrm1l1server titfcrm1l1server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/titfcrm1l2server titfcrm1l2server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qitfcrm1l1server qitfcrm1l1server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qitfcrm1l2server qitfcrm1l2server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qitfcrm1l3server qitfcrm1l3server 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xcscrm1l2server  xcscrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xcscrm1l3server  xcscrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xcscrm1l4server  xcscrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tcscrm1l3server  tcscrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tcscrm1l4server  tcscrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xcscrm1l1server  xcscrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qcscrm1l4server  qcscrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tcscrm1l1server  tcscrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tcscrm1l2server  tcscrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qcscrm1l1server  qcscrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qcscrm1l2server  qcscrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qcscrm1l3server  qcscrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xcmcrm1l2server  xcmcrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xcmcrm1l3server  xcmcrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xcmcrm1l4server  xcmcrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tcmcrm1l3server  tcmcrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tcmcrm1l4server  tcmcrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xcmcrm1l1server  xcmcrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tcmcrm1l2server  tcmcrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qcmcrm1l4server  qcmcrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tcmcrm1l1server  tcmcrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qcmcrm1l2server  qcmcrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qcmcrm1l3server  qcmcrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qcmcrm1l1server  qcmcrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xcccrm1l3server  xcccrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xcccrm1l4server  xcccrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xcccrm1l1server  xcccrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xcccrm1l2server  xcccrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tcccrm1l2server  tcccrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tcccrm1l3server  tcccrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tcccrm1l4server  tcccrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qcccrm1l3server  qcccrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qcccrm1l4server  qcccrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tcccrm1l1server  tcccrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qcccrm1l1server  qcccrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qcccrm1l2server  qcccrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xamcrm1l4server  xamcrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xamcrm1l2server  xamcrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xamcrm1l3server  xamcrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tamcrm1l3server  tamcrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tamcrm1l4server  tamcrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/xamcrm1l1server  xamcrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tamcrm1l1server  tamcrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/tamcrm1l2server  tamcrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qamcrm1l2server  qamcrm1l2server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qamcrm1l3server  qamcrm1l3server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qamcrm1l4server  qamcrm1l4server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qamcrm1l1server  qamcrm1l1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/qrmkil1server  qrmkil1server  
ln -s -f $BUDE_HOME/frame/mwsvc/bin/trmkil1server  trmkil1server  

ln -s -f $BUDE_HOME/frame/mwsvc/bin/itfbkhserver  itfbkhserver 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/itfcchserver  itfcchserver 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/itfccoserver  itfccoserver 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/itfdkhserver  itfdkhserver 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/itfdmhserver  itfdmhserver 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/itfdmoserver  itfdmoserver 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/itfibhserver  itfibhserver 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/itfiboserver  itfiboserver 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/itfpbhserver  itfpbhserver 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/itfpthserver  itfpthserver 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/itfsmhserver  itfsmhserver 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/itfsphserver  itfsphserver 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/itfuahserver  itfuahserver 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/itfwbhserver  itfwbhserver 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/itfwchserver  itfwchserver 
                
ln -s -f $BUDE_HOME/frame/mwsvc/bin/itfbkhserver  itfbkhserver 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/itfsphserver  itfsphserver 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/itfvphserver  itfvphserver
ln -s -f $BUDE_HOME/frame/mwsvc/bin/itftuhserver  itftuhserver 
ln -s -f $BUDE_HOME/frame/mwsvc/bin/itfsbhserver  itfsbhserver
ln -s -f $BUDE_HOME/frame/mwsvc/bin/itfjshserver  itfjshserver 


ln -s -f $BUDE_HOME/syscomp/bin/mwnamingserver $APP_PATH/bin/mwnamingserver

ln -s -f $BUDE_HOME/bizcomp/lib/libbackupdatetask.sl $APP_PATH/lculib/libbackupdatetask.sl
ln -s -f $BUDE_HOME/bizcomp/lib/libsmAuthsecu.sl $APP_PATH/lculib/libsmAuthsecu.sl
ln -s -f $BUDE_HOME/bizcomp/lib/libsmOrgMgr.sl $APP_PATH/lculib/libsmOrgMgr.sl
ln -s -f $BUDE_HOME/bizcomp/lib/libsysupdate.sl $APP_PATH/lculib/libsysupdate.sl
ln -s -f $BUDE_HOME/bizcomp/lib/libsysweb.sl $APP_PATH/lculib/libsysweb.sl

ln -s -f $BUDE_HOME/bizcomp/lib/libbackupdatetask.so $APP_PATH/lculib/libbackupdatetask.so
ln -s -f $BUDE_HOME/bizcomp/lib/libsmAuthsecu.so $APP_PATH/lculib/libsmAuthsecu.so
ln -s -f $BUDE_HOME/bizcomp/lib/libsmOrgMgr.so $APP_PATH/lculib/libsmOrgMgr.so
ln -s -f $BUDE_HOME/bizcomp/lib/libsysupdate.so $APP_PATH/lculib/libsysupdate.so
ln -s -f $BUDE_HOME/bizcomp/lib/libsysweb.so $APP_PATH/lculib/libsysweb.so

