/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "types_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>



int _ktypesValues[] = {
  types::e_t1,
  types::e_t2
};
const char* _ktypesNames[] = {
  "e_t1",
  "e_t2"
};
const std::map<int, const char*> _types_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(2, _ktypesValues, _ktypesNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));


